[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  # Security headers
  [headers."/*"]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

  # Cache static assets
  [headers."/static/*"]
    Cache-Control = "public, max-age=31536000, immutable"

  # Cache HTML files
  [headers."/*.html"]
    Cache-Control = "public, max-age=0, must-revalidate"
